version: "3.9"
services:
  activation_base:
    build: .
    image: knowledgebase_salaryprediction
    container_name: knowledgebase_salaryprediction
    volumes:
       - ai_system:/tmp
    command:
    - sh
    - "-c"
    - |
      rm -rf /tmp/knowledgeBase/ && cp -r /knowledgeBase/ /tmp/knowledgeBase/
    
    
volumes:
  ai_system:
    external: true