version: "3.9"
services:
  activation_base:
    build: .
    image: activationbase_salaryprediction
    container_name: activationbase_salaryprediction
    volumes:
       - ai_system:/tmp
    command:
    - sh
    - "-c"
    - |
      rm -rf /tmp/activationBase/ && cp -r /activationBase/ /tmp/;
    
volumes:
  ai_system:
    external: true
