# Use busybox as the base image
FROM busybox

# Create the necessary directory inside the container
RUN mkdir -p /tmp/activationBase

# Copy the activation_data.csv file into the container
COPY ../data/activation_data.csv /tmp/activationBase/

# Copy the README.md for documentation
COPY README.md /tmp/activationBase/README.md