# Use busybox as the base image
FROM busybox

# Create the necessary directories inside the container
WORKDIR /activationBase

# Copy the CSV files into the container
COPY ../data/activation_data.csv /activationBase/

# Copy the README.md for documentation
COPY README.md /activationBase/README.md

